import type { EmploymentStatus } from '../constants/index.js';

export interface Employee {
    employeeId: number;
    userId: number;
    employeeCode: string;
    jobRole: string;
    defaultShiftHours: string;
    hourlyRate: string;
    dailyPay: string;
    employmentStatus: EmploymentStatus;
    createdAt: Date;
    updatedAt: Date | null;
}
export interface EmployeeProfile extends Employee {
    username: string;
    fullName: string;
}

export interface CreateEmployeeInput {
    userId: number;
    employeeCode: string;
    jobRole: string;
    defaultShiftHours: string;
    hourlyRate: string;
}

/**
 * Used for creating an employee profile when registering an employee. 
 * The userId is generated by the createUser service and passed to the createEmployee repository function.
 */
export interface RegisterEmployeeInput {
    username: string;
    password: string;
    fullName: string;
    employeeCode: string;
    jobRole: string;
    defaultShiftHours: string;
    hourlyRate: string;
}

export interface UpdateEmployeeInput {
    jobRole?: string;
    defaultShiftHours?: string;
    hourlyRate?: string;
    employmentStatus?: EmploymentStatus;
}
